Feature/23 footer
Lordpluha/GameBlog pull request #68
Opened 2024-02-04 13:18 UTC by annymal

2024-02-04 13:24 UTC, Lordpluha commented on client/src/components/ui/Container.tsx
> +export const Container = ({ children }: TContainerProps) => {
You can use Container: FC<PropsWithChildren>

2024-02-04 13:26 UTC, Lordpluha commented on client/src/components/ui/footer/Footer.module.scss
> +	@apply bg-[#161B1D] text-white absolute bottom-0 w-full font-["Rubik"]
use variables

2024-02-04 13:26 UTC, Lordpluha commented on client/src/components/ui/footer/Footer.module.scss
> +	@apply bg-[#161B1D] text-white absolute bottom-0 w-full font-["Rubik"]
use relative position

2024-02-04 13:26 UTC, Lordpluha commented on client/src/components/ui/footer/Footer.module.scss
> +	@apply bg-[#161B1D] text-white absolute bottom-0 w-full font-["Rubik"]
use font from tailwind

2024-02-04 13:27 UTC, Lordpluha commented on client/src/components/ui/footer/Footer.module.scss
> +	@apply mt-[24px] mx-auto relative px-[32px] pb-[58px] max-w-[1280px];
try not to use px

2024-02-10 16:21 UTC, Lordpluha requested changes

2024-02-10 16:21 UTC, Lordpluha commented on client/src/components/ui/Container.tsx
Delete this file

2024-02-10 16:21 UTC, Lordpluha commented on client/.storybook/theme/assets/icon-age.png
move this file to needed location in module in ui/ slice

2024-02-10 16:21 UTC, Lordpluha commented on client/src/pages/Layout.tsx
> +import { Footer } from '@widgets/footer'
Big letter start naming

2024-02-10 19:46 UTC, annymal commented on client/src/widgets/footer/ui/Footer.tsx
не работает картинка по такому пути.
не знаю, почему.

2024-02-28 18:22 UTC, Lordpluha approved these changes

2024-02-29 07:47 UTC, merged